### ISSUE TITLE
Are you set-up for REX-Ray?

### ISSUE THREAD

**Issue by smitchell** [dcos-labs/dcos-gce#13]
I'm getting "Error looking up volume plugin rexray: plugin not found." running DC/OS on Google Compute Engine?

I added this to template/config.yaml on the bootstrap node:

```
rexray:
  storageDrivers:
  - gce
gce:
  keyfile: /certdir/mobilecapitalgroup-dc-os-3bbd29c9ab02.json
```

I put my private key at the path above on master0.

I added this to my application configuration JSON:

```
    "volumes": [
      {
        "containerPath": "/var/jenkins_home",
        "external": {
          "name": "jenkins",
          "provider": "dvdi",
          "options": {
            "dvdi/driver": "rexray"
          }
        },
        "mode": "RW"
      },
      {
        "containerPath": "/opt/mesosphere",
        "hostPath": "/opt/mesosphere",
        "mode": "RO"
      }
    ]
]]
```

But when I try to start Jenkins I get this error:

> docker: Error response from daemon: create jenkins: create jenkins: Error looking up volume plugin rexray: plugin not found.
> See 'docker run --help'.
> W1203 18:46:44.996757 18633 logging.cpp:91] RAW: Received signal SIGTERM from process 2548 of user 0; exiting
> 

Checking rexray on master0 I see that it isn't running:

```
# /opt/mesosphere/bin/rexray service status
REX-Ray is stopped

```
I tried adding gce to /etc/rexray/config.yml

```
rexray:
  loglevel: info
  storageDrivers:
  - gce
  gce:
    keyFile: /certdir/mobilecapitalgroup-dc-os-3bbd29c9ab02.json
  modules:
    default-admin:
      host: tcp://127.0.0.1:61003
    default-docker:
      disabled: true

```
But it still won't start:

[root@master0 rexray]# /opt/mesosphere/bin/rexray service start
INFO[0000] [linux]                                      
INFO[0000] [docker]                                     
INFO[0000] [gce]                                        
INFO[0000] os driver initialized                         moduleName= provider=linux
INFO[0000] docker volume driver initialized              availabilityZone= iops= moduleName= provider=docker size= volumeRootPath=/data volumeType=
FATA[0000] Could not read service account credentials file,  => {open : no such file or directory}  keyFile= moduleName= provider=gce

Any suggestions?
